version: "3.9"
services:
  angular:
    build:
      context: ./ngapp
      dockerfile: Dockerfile
    container_name: ngapp
    ports:
      - "4200:80"
    restart: unless-stopped

  nextjs:
    build:
      context: ./nxapp14
      dockerfile: Dockerfile
    container_name: nxapp14
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
